// ── Avatars ─────────────────────────────────────────────
export const AVATARS = ["🐱","🪲","🐸","🦊","🐼","🐨","🦁","🐯"];

// ── Game metadata ────────────────────────────────────────
export const META = {
  sequence: { title:"Urutan Perintah",   icon:"📋", color:"#FF9F43" },
  robot:    { title:"Gerak Robot",       icon:"🤖", color:"#3B82F6" },
  pattern:  { title:"Pola & Perulangan", icon:"🔄", color:"#8B5CF6" },
  typing:   { title:"Ketik Kodenya!",    icon:"⌨️",  color:"#10B981" },
};

// ── Sequence levels ──────────────────────────────────────
export const SEQ_LV = [
  { badge:"Mudah", story:"Kaysa mau masak mie. Urutkan langkahnya!",
    steps:["Siapkan mie, Panci, Piring",
        "Rebus air dan Tunggu mendidih",
        "Makan",
        "Masukan air dalam panci",
        "Masukan mie kedalam panci",
        "Rebus mie hingga matang",
        "Tuang mie ke mangkok"], correct:[0,3,1,4,5,6,2] },
  { badge:"Mudah", story:"Bayu mau menyalakan Berangkat sekolah. Urutkan Langkahnya!",
    steps:["Sarapan",
        "Mandi",
        "Berangkat sekolah",
        "Memakai Seragam Sekolah",
        "Berpamitan Ke Orang tua",
        "Memakai Sepatu",
        "Menyiapkan buku dan tas"], correct:[1,3,6,0,5,4,2] },
  { badge:"Mudah", story:"Royan mau menyikat gigi. Urutkan langkahnya!",
    steps:["Sikat Gigi",
        "Ambil Sikat Gigi dan Pasta Gigi",
        "Oleskan Pasta Gigi ke Sikat gigi",
        "Buka Pasta Gigi",
        "Kumur Kumur dan Bilas sampai bersih"], correct:[1,3,2,0,4] },
  { badge:"Mudah", story:"Ana mau mandi pagi. Urutkan langkahnya!",
    steps:["Keringkan badan","Masuk kamar mandi","Sabun badan","Bilas dengan air","Pakai handuk"], correct:[1,3,2,0,4] },
  { badge:"Sedang", story:"Robot mau memasak mie instan. Urutkan caranya!",
    steps:["Masukkan mie ke air","Rebus air sampai mendidih","Tuang bumbu","Mie siap dimakan","Tiriskan air"], correct:[1,0,4,2,3] },
  { badge:"Sedang", story:"Dina mau download aplikasi baru. Urutkan langkahnya!",
    steps:["Install aplikasi","Buka Play Store","Klik Download","Cari nama aplikasi","Buka aplikasinya"], correct:[1,3,2,0,4] },
  { badge:"Sedang", story:"Robot mau membuat website sederhana. Urutkan caranya!",
    steps:["Simpan file","Tulis kode HTML","Buka browser","Buka text editor","Lihat hasilnya"], correct:[3,1,0,2,4] },
  { badge:"Susah", story:"Pak Guru mau mencetak dokumen. Urutkan langkahnya!",
    steps:["Ambil kertas hasil cetak","Pastikan printer nyala","Klik Print","Buka dokumen","Pilih printer yang benar"], correct:[3,1,4,2,0] },
  { badge:"Susah", story:"Robot mau mengirim email penting. Urutkan langkahnya!",
    steps:["Klik Kirim","Buka aplikasi email","Tulis isi pesan","Klik Tulis Email Baru","Isi alamat email tujuan"], correct:[1,3,4,2,0] },
  { badge:"Susah", story:"Rina mau membuat aplikasi sederhana. Urutkan tahapannya!",
    steps:["Publikasikan aplikasi","Rencanakan fitur","Tulis kode program","Uji coba dan perbaiki","Desain tampilan"], correct:[1,4,2,3,0] },
];

// ── Pattern levels ───────────────────────────────────────
export const PAT_LV = [
  { badge:"Mudah", sit:"Lihat pola warna berikut:", pattern:["🔴","🔵","🔴","🔵","🔴","?"],
    q:"Warna apa yang berikutnya?", opts:["🔴 Merah","🔵 Biru","🟡 Kuning","🟢 Hijau"], correct:1,
    explain:"Polanya bergantian: Merah → Biru → Merah → Biru. Jadi berikutnya adalah Biru! 🔵" },
  { badge:"Mudah", sit:"Robot melompat mengikuti pola:", pattern:["⭐","⭐","🌙","⭐","⭐","🌙","⭐","⭐","?"],
    q:"Giliran ke-9 apa?", opts:["⭐ Bintang","🌙 Bulan","☀️ Matahari","❤️ Hati"], correct:1,
    explain:"Polanya: Bintang, Bintang, Bulan — diulang. Giliran ke-9 = posisi ke-3 dalam pola = Bulan! 🌙" },
  { badge:"Mudah", sit:"Lihat barisan angka ini:", pattern:["2","4","6","8","?"],
    q:"Angka selanjutnya adalah?", opts:["9","10","11","12"], correct:1,
    explain:"Polanya bertambah 2 setiap langkah. 2+2=4, 4+2=6, 6+2=8, 8+2=10! 🔢" },
  { badge:"Mudah", sit:"Ani menanam bunga setiap hari. Hari ke-1 tanam 2, hari ke-2 tanam 4, hari ke-3 tanam 6.",
    visual:["🌸×2","🌸×4","🌸×6","🌸×?"],
    q:"Hari ke-4 berapa bunga?", opts:["6 bunga","7 bunga","8 bunga","10 bunga"], correct:2,
    explain:"Polanya bertambah 2 setiap hari! 2→4→6→8. Hari ke-4 = 8 bunga! 🌸" },
  { badge:"Sedang", sit:"Riko menghias kelas dengan bendera warna-warni:", pattern:["🟥","🟨","🟦","🟥","🟨","🟦","🟥","?"],
    q:"Bendera ke-8 warnanya apa?", opts:["Merah","Kuning","Biru","Hijau"], correct:1,
    explain:"Polanya: Merah→Kuning→Biru, lalu diulang. Bendera ke-8 = urutan ke-2 = Kuning! 🟨" },
  { badge:"Sedang", sit:"Sebuah lift naik dari lantai 1. Setiap menit naik 3 lantai.",
    visual:["Menit 0: Lantai 1","Menit 1: Lantai 4","Menit 2: Lantai 7","Menit 3: Lantai ?"],
    q:"Di menit ke-3, lift ada di lantai berapa?", opts:["Lantai 8","Lantai 9","Lantai 10","Lantai 12"], correct:2,
    explain:"Mulai dari 1: 1+3=4, 4+3=7, 7+3=10. Menit ke-3 = lantai 10! 🛗" },
  { badge:"Sedang", sit:"Robot melompat mengikuti pola:", pattern:["🐸","🐸","⭐","🐸","🐸","⭐","🐸","🐸","?"],
    q:"Giliran ke-9 apa?", opts:["Katak 🐸","Bintang ⭐","Bulan 🌙","Hati ❤️"], correct:1,
    explain:"Polanya: Katak, Katak, Bintang. Giliran ke-9 = posisi ke-3 dalam pola = Bintang! ⭐" },
  { badge:"Sedang", sit:"Robot mengecat pagar. Ada 12 pagar, setiap menit dia mengecat 4 pagar.",
    visual:["Menit 1: 4 pagar","Menit 2: 8 pagar","Menit 3: 12 pagar","Total: selesai!"],
    q:"Berapa menit robot mengecat semua pagar?", opts:["2 menit","3 menit","4 menit","6 menit"], correct:1,
    explain:"Robot cat 4 pagar per menit. 12÷4 = 3 menit untuk selesaikan semuanya! 🎨" },
  { badge:"Susah", sit:"Sekolah punya 3 kelas. Setiap kelas punya 5 meja. Setiap meja punya 2 kursi.",
    visual:["🏫 3 kelas","×5 meja per kelas","×2 kursi per meja","= ? kursi total"],
    q:"Total berapa kursi di sekolah?", opts:["15 kursi","25 kursi","30 kursi","45 kursi"], correct:2,
    explain:"3 kelas × 5 meja = 15 meja. 15 meja × 2 kursi = 30 kursi total! 🪑" },
  { badge:"Susah", sit:"Robot berjalan. Langkah 1=1m, langkah 2=2m, langkah 3=4m, langkah 4=8m.",
    visual:["Langkah 1: 1m","Langkah 2: 2m","Langkah 3: 4m","Langkah 4: ?"],
    q:"Langkah ke-5 berapa meter?", opts:["10m","12m","16m","20m"], correct:2,
    explain:"Polanya lipat dua setiap langkah! 1→2→4→8→16. Langkah ke-5 = 16m! 🚶" },
];

// ── Typing levels ────────────────────────────────────────
export const TYP_LV = [
  { badge:"Mudah", story:"Robot mau menyapa dengan kata 'Halo'.",
    example:'print("Halo")', task:'Ketik kode untuk mencetak kata "Pagi".',
    answer:'print("Pagi")',
    explain:'print() dipakai untuk menampilkan teks. Ganti isinya dengan kata yang diinginkan!' },
  { badge:"Mudah", story:"Robot menyimpan umur seseorang.",
    example:'umur = 10', task:'Ketik kode untuk menyimpan umur = 12.',
    answer:'umur = 12',
    explain:'Kita simpan angka ke dalam kotak bernama umur. Ganti angkanya sesuai perintah!' },
  { badge:"Mudah", story:"Robot menyimpan nama teman.",
    example:'nama = "Budi"', task:'Ketik kode untuk menyimpan nama = "Ani".',
    answer:'nama = "Ani"',
    explain:'Tanda = artinya simpan. Di sini kita simpan kata Ani ke dalam kotak bernama nama.' },
  { badge:"Mudah", story:"Robot mengucapkan salam 3 kali berturut-turut.",
    example:'print("Salam")\nprint("Salam")\nprint("Salam")',
    task:'Ketik kode untuk mencetak kata "Hore" sebanyak 3 kali.',
    answer:'print("Hore")\nprint("Hore")\nprint("Hore")',
    explain:'Kita bisa panggil print() berkali-kali. Setiap print() mencetak satu baris!' },
  { badge:"Sedang", story:"Robot menjumlahkan dua angka.",
    example:'hasil = 3 + 4\nprint(hasil)',
    task:'Ketik kode untuk menjumlahkan 5 + 6 dan tampilkan hasilnya.',
    answer:'hasil = 5 + 6\nprint(hasil)',
    explain:'Kita simpan hasil penjumlahan ke variabel hasil, lalu print() untuk menampilkannya. Hasilnya 11!' },
  { badge:"Sedang", story:"Robot mencetak angka 1 sampai 3.",
    example:'print(1)\nprint(2)\nprint(3)',
    task:'Ketik kode untuk mencetak angka 4, 5, dan 6.',
    answer:'print(4)\nprint(5)\nprint(6)',
    explain:'Setiap print() mencetak satu angka. Ganti angka 1,2,3 menjadi 4,5,6!' },
  { badge:"Sedang", story:"Robot menyapa nama seseorang.",
    example:'nama = "Dito"\nprint("Halo " + nama)',
    task:'Ketik kode yang sama tapi untuk nama = "Rina".',
    answer:'nama = "Rina"\nprint("Halo " + nama)',
    explain:'Variabel nama disimpan dulu, lalu disambung dengan kata Halo menggunakan tanda +. Hasilnya: Halo Rina!' },
  { badge:"Sedang", story:"Robot menghitung banyaknya buku.",
    example:'buku = 5\nbuku = buku + 3\nprint(buku)',
    task:'Ketik kode yang sama tapi mulai dari buku = 10, tambah 2.',
    answer:'buku = 10\nbuku = buku + 2\nprint(buku)',
    explain:'buku = buku + 2 artinya nilai buku lama ditambah 2. 10 + 2 = 12. Hasilnya 12!' },
];